[package]
name = "kord"
version = "0.4.2"
edition = "2021"
authors = ["Aaron Roney <twitchax@gmail.com>"]
license = "MIT"
description = "A tool to easily explore music theory principles."
readme = "README.md"
homepage = "https://github.com/twitchax/kord"
repository = "https://github.com/twitchax/kord"
keywords = ["cli", "music", "theory", "jazz", "chords"]
categories = ["command-line-utilities"]

[features]
default = ["cli", "audio"]
cli = ["clap", "futures"]
audio = ["rodio", "cpal", "rustfft", "futures-timer"]
wasm = ["rodio/wasm-bindgen"]
debug = []
plot = ["plotters"]

[lib]
name = "klib"
path = "src/lib.rs"

[[bin]]
name = "kord"
path = "src/bin.rs"
required-features = ["cli"]

[dependencies]
once_cell = "1.16.0"
paste = "1.0.9"
clap = { version = "4.0.29", features = ["derive"], optional = true }
anyhow = "1.0.66"
rodio = { version = "0.16.0", default-features = false, optional = true }
cpal = { version = "0.14.2", optional = true }
pest = "2.5.1"
pest_derive = "2.5.1"
rustfft = { version = "6.1.0", optional = true }
futures-timer = { version = "3.0.2", optional = true }
futures = { version = "0.3.25", optional = true }
plotters = { version = "0.3.4", optional = true }
which = "4.3.0"

[dev-dependencies]
pretty_assertions = "1.3.0"
